services:
  unikraft-ui:
    image: ghcr.io/debbide/unikraft-ui:latest
    container_name: my-unikraft-ui
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:18689:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
